Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
  0%|                                                                                                                                                                    | 0/7910 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/data/chuak/mmser/src/multi_modal_ser/finetune_encoder/audio_video/train_roi_aug.py", line 293, in <module>
    main()
  File "/data/chuak/mmser/src/multi_modal_ser/finetune_encoder/audio_video/train_roi_aug.py", line 281, in main
    trainer.train()
  File "/data/chuak/mmser/lib/python3.10/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/data/chuak/mmser/lib/python3.10/site-packages/transformers/trainer.py", line 1854, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/transformers/trainer.py", line 2728, in training_step
    loss = self.compute_loss(model, inputs)
  File "/data/chuak/mmser/src/multi_modal_ser/finetune_encoder/audio_video/avhubert_trainer.py", line 12, in compute_loss
    outputs = model(**inputs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 110, in parallel_apply
    output.reraise()
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
NameError: Caught NameError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in _worker
    output = module(*input, **kwargs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/chuak/mmser/src/multi_modal_ser/finetune_encoder/audio_video/avhubert_classifier.py", line 38, in forward
    outputs = self.encoder.extract_finetune(
  File "/data/chuak/mmser/src/multi_modal_ser/finetune_encoder/audio_video/av_hubert/avhubert/hubert.py", line 710, in extract_finetune
    features_video = self.forward_features(src_video, modality='video')
  File "/data/chuak/mmser/src/multi_modal_ser/finetune_encoder/audio_video/av_hubert/avhubert/hubert.py", line 541, in forward_features
    features = extractor(source)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/chuak/mmser/src/multi_modal_ser/finetune_encoder/audio_video/av_hubert/avhubert/hubert.py", line 326, in forward
    x = self.resnet(x)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/chuak/mmser/src/multi_modal_ser/finetune_encoder/audio_video/av_hubert/avhubert/resnet.py", line 161, in forward
    with torch.no_grad():
NameError: name 'torch' is not defined
Traceback (most recent call last):
  File "/data/chuak/mmser/src/multi_modal_ser/finetune_encoder/audio_video/train_roi_aug.py", line 293, in <module>
    main()
  File "/data/chuak/mmser/src/multi_modal_ser/finetune_encoder/audio_video/train_roi_aug.py", line 281, in main
    trainer.train()
  File "/data/chuak/mmser/lib/python3.10/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/data/chuak/mmser/lib/python3.10/site-packages/transformers/trainer.py", line 1854, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/transformers/trainer.py", line 2728, in training_step
    loss = self.compute_loss(model, inputs)
  File "/data/chuak/mmser/src/multi_modal_ser/finetune_encoder/audio_video/avhubert_trainer.py", line 12, in compute_loss
    outputs = model(**inputs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 110, in parallel_apply
    output.reraise()
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
NameError: Caught NameError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in _worker
    output = module(*input, **kwargs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/chuak/mmser/src/multi_modal_ser/finetune_encoder/audio_video/avhubert_classifier.py", line 38, in forward
    outputs = self.encoder.extract_finetune(
  File "/data/chuak/mmser/src/multi_modal_ser/finetune_encoder/audio_video/av_hubert/avhubert/hubert.py", line 710, in extract_finetune
    features_video = self.forward_features(src_video, modality='video')
  File "/data/chuak/mmser/src/multi_modal_ser/finetune_encoder/audio_video/av_hubert/avhubert/hubert.py", line 541, in forward_features
    features = extractor(source)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/chuak/mmser/src/multi_modal_ser/finetune_encoder/audio_video/av_hubert/avhubert/hubert.py", line 326, in forward
    x = self.resnet(x)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/chuak/mmser/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/chuak/mmser/src/multi_modal_ser/finetune_encoder/audio_video/av_hubert/avhubert/resnet.py", line 161, in forward
    with torch.no_grad():
NameError: name 'torch' is not defined